{
  config,
  pkgs,
  ...
}: {
  environment.systemPackages = with pkgs; [
    ((emacsPackagesFor emacs-pgtk).emacsWithPackages (epkgs: [
      epkgs.company
      epkgs.comment-dwim-2
      epkgs.consult
      epkgs.csv-mode
      epkgs.direnv
      epkgs.elfeed
      epkgs.ef-themes
      epkgs.embark
      epkgs.embark-consult
      epkgs.evil
      epkgs.evil-goggles
      epkgs.evil-surround
      epkgs.git-timemachine
      epkgs.go-mode
      epkgs.helpful
      epkgs.ledger-mode
      epkgs.logos
      epkgs.macrostep
      epkgs.magit
      epkgs.modus-themes
      epkgs.multi-vterm
      epkgs.multiple-cursors
      epkgs.nix-ts-mode
      epkgs.notmuch
      epkgs.olivetti
      epkgs.orderless
      epkgs.org-bullets
      epkgs.paren-face
      epkgs.restclient
      epkgs.rg
      epkgs.spacious-padding
      epkgs.treesit-grammars.with-all-grammars
      epkgs.vertico
      epkgs.vterm
    ]))
  ];
}
